Controllers/ContatoController.cs
using Microsoft.AspNetCore.Mvc;

namespace OneStore.Controllers
{
    public class ContatoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/RoupaController.cs
using Microsoft.AspNetCore.Mvc;
using OneStore.Models;
using OneStore.Repositories.Interfaces;
using OneStore.ViewModels;

namespace OneStore.Controllers
{
    public class RoupaController : Controller
    {
        private readonly IRoupaRepository _roupaRepository;

        public RoupaController(IRoupaRepository roupaRepository)
        {
            _roupaRepository = roupaRepository;
        }

        public IActionResult List(string categoria)
        {
            IEnumerable<Roupa> roupas;
            string categoriaAtual = string.Empty;

            if (string.IsNullOrEmpty(categoria))
            {
                roupas = _roupaRepository.GetRoupas.OrderBy(r => r.RoupaId);
                categoriaAtual = "Todos os lanches";
            }
            else
            {
                roupas = _roupaRepository.GetRoupas.Where(o => o.Categoria.CategoriaNome.Equals(categoria)).OrderBy(r => r.RoupaNome);

                categoriaAtual = categoria;
            }

            var roupaListViewModel = new RoupaListViewModel
            {
                Roupas = roupas,
                Categoria = categoriaAtual
            };

            return View(roupaListViewModel);
        }

        public IActionResult Details(int roupaId)
        {
            var roupa = _roupaRepository.GetRoupas.FirstOrDefault(r => r.RoupaId == roupaId);
            return View(roupa);
        }

        public ViewResult Search(string searchString)
        {
            IEnumerable<Roupa> roupas;
            string categoriaAtual = string.Empty;

            if(string.IsNullOrEmpty(searchString))
            {
                roupas = _roupaRepository.GetRoupas.OrderBy(p => p.RoupaId);
                categoriaAtual = "Todas as roupas";
            }
            else
            {
                roupas = _roupaRepository.GetRoupas.Where(p => p.RoupaNome.ToLower().Contains(searchString.ToLower()));

                if (roupas.Any())
                {
                    categoriaAtual = "Roupas";
                }
                else
                {
                    categoriaAtual = "Nenhuma roupa foi encontrada";
                }
            }

            return View("~/Views/Roupa/List.cshtml", new RoupaListViewModel
            {
                Roupas = roupas,
                Categoria = categoriaAtual
            });
        }
    }
}

Views/Shared/_Carousel.cshtml
<div id="carouselRoupas" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="~/images/CamisetaAzul.jpg" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>First slide label</h5>
        <p>Some representative placeholder content for the first slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="~/images/CamisetaCinza.jpg" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Second slide label</h5>
        <p>Some representative placeholder content for the second slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="~/images/CalcaJeansEscura.jpg" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Third slide label</h5>
        <p>Some representative placeholder content for the third slide.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselRoupas" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselRoupas" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] OneStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OneStore.styles.css" asp-append-version="true" />
    <link rel="icon" type="image/png" href="~/images/IconeNavegador.png" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <img src="~/images/logoone.png" style="width: 1%" />
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> OneStore </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @await Component.InvokeAsync("CarrinhoCompraResumo")
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Contato" asp-action="Index">Contato</a>
                        </li>
                        <li class="nav-item">
                            @await Component.InvokeAsync("CategoriaMenu")
                        </li>
                        <li class="nav-item">
                            <form class="navbar-form navbar-right" asp-controller="Roupa" asp-action="Search" method="get">
                                <input type="text" class="form-control" placeholder="Procurar produto" name="searchString" value="@ViewData["searchString"]" />
                            </form>
                        </li>
                        <li class="nav-item">
                            @await Html.PartialAsync("_LoginPartial")
                        </li>
                        <li class="nav-item">
                            @if (User.IsInRole("Admin"))
                            {
                                <a class="nav-link text-light" asp-area="Area" asp-controller="Admin" asp-action="Index">Admin</a>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer style="color:white">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <div class="row" style="width: 100%;">
                    <div class="col-6">
                        <h4> &copy; 2024 - OneStore </h4>
                    </div>
                    <div class="col-6">
                        <ul>
                            <li>Av. Amazonas, 650 - Centro, Belo Horizonte/MG</li>
                            <li>+55 (31) 98757-8298</li>
                            <li><a asp-controller="Contato" asp-action="Index">Contato</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_RoupaResumo.cshtml
@model Roupa

<div class="col-sm-4 col-md-4 col-lg-4">
    <h3> @Model.RoupaNome </h3>

    <p><img src="@Model.RoupaUrlImagem" class="img-fluid"/></p>
    <h5> Preço: @Model.RoupaPreco.ToString("c") </h5>
    <p>@Model.RoupaDescricao</p>

    <div>
        <p class="btn btn-group align-content-lg-end">
            <a asp-controller="Roupa" asp-action="Details" asp-route-roupaId="@Model.RoupaId" class="btn btn-outline-info">Detalhes</a>
            <a class="btn btn-primary" id="cartButton" asp-controller="CarrinhoCompra" asp-action="AdicionarItemNoCarrinhoCompra" asp-route-roupaId="@Model.RoupaId">
                Incluir no carrinho
            </a>
        </p>
    </div>
</div>